// Code generated by protoc-gen-go.
// source: github.com/libreoscar/btcwatch/message/schema.proto
// DO NOT EDIT!

/*
Package message is a generated protocol buffer package.

It is generated from these files:
	github.com/libreoscar/btcwatch/message/schema.proto

It has these top-level messages:
	ValueTransfer
	OpReturnMsg
	TxResult
	ProcessedTx
	ProcessedBlock
*/
package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type ValueTransfer struct {
	Address string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	Value   uint64 `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
}

func (m *ValueTransfer) Reset()                    { *m = ValueTransfer{} }
func (m *ValueTransfer) String() string            { return proto.CompactTextString(m) }
func (*ValueTransfer) ProtoMessage()               {}
func (*ValueTransfer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type OpReturnMsg struct {
	Msg string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
}

func (m *OpReturnMsg) Reset()                    { *m = OpReturnMsg{} }
func (m *OpReturnMsg) String() string            { return proto.CompactTextString(m) }
func (*OpReturnMsg) ProtoMessage()               {}
func (*OpReturnMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type TxResult struct {
	// Types that are valid to be assigned to Result:
	//	*TxResult_Transfer
	//	*TxResult_Msg
	Result isTxResult_Result `protobuf_oneof:"Result"`
}

func (m *TxResult) Reset()                    { *m = TxResult{} }
func (m *TxResult) String() string            { return proto.CompactTextString(m) }
func (*TxResult) ProtoMessage()               {}
func (*TxResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type isTxResult_Result interface {
	isTxResult_Result()
}

type TxResult_Transfer struct {
	Transfer *ValueTransfer `protobuf:"bytes,1,opt,name=transfer,oneof"`
}
type TxResult_Msg struct {
	Msg *OpReturnMsg `protobuf:"bytes,2,opt,name=msg,oneof"`
}

func (*TxResult_Transfer) isTxResult_Result() {}
func (*TxResult_Msg) isTxResult_Result()      {}

func (m *TxResult) GetResult() isTxResult_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *TxResult) GetTransfer() *ValueTransfer {
	if x, ok := m.GetResult().(*TxResult_Transfer); ok {
		return x.Transfer
	}
	return nil
}

func (m *TxResult) GetMsg() *OpReturnMsg {
	if x, ok := m.GetResult().(*TxResult_Msg); ok {
		return x.Msg
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*TxResult) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _TxResult_OneofMarshaler, _TxResult_OneofUnmarshaler, _TxResult_OneofSizer, []interface{}{
		(*TxResult_Transfer)(nil),
		(*TxResult_Msg)(nil),
	}
}

func _TxResult_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*TxResult)
	// Result
	switch x := m.Result.(type) {
	case *TxResult_Transfer:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Transfer); err != nil {
			return err
		}
	case *TxResult_Msg:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Msg); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("TxResult.Result has unexpected type %T", x)
	}
	return nil
}

func _TxResult_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*TxResult)
	switch tag {
	case 1: // Result.transfer
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ValueTransfer)
		err := b.DecodeMessage(msg)
		m.Result = &TxResult_Transfer{msg}
		return true, err
	case 2: // Result.msg
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(OpReturnMsg)
		err := b.DecodeMessage(msg)
		m.Result = &TxResult_Msg{msg}
		return true, err
	default:
		return false, nil
	}
}

func _TxResult_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*TxResult)
	// Result
	switch x := m.Result.(type) {
	case *TxResult_Transfer:
		s := proto.Size(x.Transfer)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *TxResult_Msg:
		s := proto.Size(x.Msg)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ProcessedTx struct {
	Txid   string      `protobuf:"bytes,1,opt,name=Txid" json:"Txid,omitempty"`
	Result []*TxResult `protobuf:"bytes,2,rep,name=Result" json:"Result,omitempty"`
}

func (m *ProcessedTx) Reset()                    { *m = ProcessedTx{} }
func (m *ProcessedTx) String() string            { return proto.CompactTextString(m) }
func (*ProcessedTx) ProtoMessage()               {}
func (*ProcessedTx) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ProcessedTx) GetResult() []*TxResult {
	if m != nil {
		return m.Result
	}
	return nil
}

type ProcessedBlock struct {
	BlockIndex int32          `protobuf:"varint,1,opt,name=BlockIndex" json:"BlockIndex,omitempty"`
	Txs        []*ProcessedTx `protobuf:"bytes,2,rep,name=Txs" json:"Txs,omitempty"`
}

func (m *ProcessedBlock) Reset()                    { *m = ProcessedBlock{} }
func (m *ProcessedBlock) String() string            { return proto.CompactTextString(m) }
func (*ProcessedBlock) ProtoMessage()               {}
func (*ProcessedBlock) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ProcessedBlock) GetTxs() []*ProcessedTx {
	if m != nil {
		return m.Txs
	}
	return nil
}

func init() {
	proto.RegisterType((*ValueTransfer)(nil), "message.ValueTransfer")
	proto.RegisterType((*OpReturnMsg)(nil), "message.OpReturnMsg")
	proto.RegisterType((*TxResult)(nil), "message.TxResult")
	proto.RegisterType((*ProcessedTx)(nil), "message.ProcessedTx")
	proto.RegisterType((*ProcessedBlock)(nil), "message.ProcessedBlock")
}

var fileDescriptor0 = []byte{
	// 271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x54, 0x90, 0xbf, 0x4f, 0xf3, 0x30,
	0x10, 0x86, 0xdb, 0xa6, 0x3f, 0xf2, 0x5d, 0xbe, 0x82, 0xb0, 0x10, 0xaa, 0x98, 0x20, 0x2c, 0x88,
	0x21, 0x91, 0xe8, 0xce, 0xd0, 0x85, 0x32, 0x20, 0x50, 0x15, 0xb1, 0x3b, 0xf6, 0x91, 0x44, 0x24,
	0x71, 0x65, 0x3b, 0xe0, 0x3f, 0x1f, 0xe3, 0xb8, 0xa1, 0x6c, 0xb6, 0xef, 0xf1, 0xf3, 0xbe, 0x3a,
	0x58, 0x17, 0x95, 0x2e, 0xbb, 0x3c, 0x61, 0xa2, 0x49, 0xeb, 0x2a, 0x97, 0x28, 0x14, 0xa3, 0x32,
	0xcd, 0x35, 0xfb, 0xa2, 0x9a, 0x95, 0x69, 0x83, 0x4a, 0xd1, 0x02, 0x53, 0xc5, 0x4a, 0x6c, 0x68,
	0xb2, 0x97, 0x42, 0x0b, 0xb2, 0xf0, 0xaf, 0x71, 0x0a, 0xcb, 0x37, 0x5a, 0x77, 0x98, 0x49, 0xda,
	0xaa, 0x77, 0x94, 0xe4, 0x14, 0x16, 0x94, 0x73, 0x69, 0xc7, 0xab, 0xf1, 0xd5, 0xf8, 0xf6, 0x1f,
	0x59, 0xc2, 0xec, 0xf3, 0x87, 0x58, 0x4d, 0xec, 0x75, 0x1a, 0x5f, 0x42, 0xf4, 0xb2, 0xdf, 0xa1,
	0xee, 0x64, 0xfb, 0xac, 0x0a, 0x12, 0x41, 0xd0, 0xa8, 0xa2, 0x47, 0x63, 0x84, 0x30, 0x33, 0x3b,
	0x54, 0x5d, 0xad, 0xc9, 0x1d, 0x84, 0xda, 0x3b, 0xdd, 0x34, 0xba, 0xbf, 0x48, 0x7c, 0x68, 0xf2,
	0x27, 0x71, 0x3b, 0x22, 0x37, 0xbd, 0x64, 0xe2, 0xb0, 0xf3, 0x01, 0x3b, 0xca, 0xd9, 0x8e, 0x36,
	0x21, 0xcc, 0x7b, 0x75, 0xfc, 0x00, 0xd1, 0xab, 0x14, 0xcc, 0x52, 0xc8, 0x33, 0x43, 0xfe, 0xc3,
	0x34, 0x33, 0x15, 0xf7, 0x75, 0xaf, 0x0f, 0x98, 0xd5, 0x05, 0x56, 0x77, 0x36, 0xe8, 0x0e, 0xd5,
	0xe2, 0x47, 0x38, 0x19, 0xfe, 0x6f, 0x6a, 0xc1, 0x3e, 0x08, 0x01, 0x70, 0x87, 0xa7, 0x96, 0xa3,
	0x71, 0xa2, 0x99, 0x15, 0x05, 0x99, 0x51, 0xde, 0xf2, 0x5b, 0xea, 0x28, 0x39, 0x9f, 0xbb, 0x65,
	0xae, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x6d, 0xda, 0xdd, 0x2f, 0x83, 0x01, 0x00, 0x00,
}
